const FLAGS: Record<string, string> = {
  // British Isles
  English: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
  Scottish: "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
  Welsh: "🏴󠁧󠁢󠁷󠁬󠁳󠁿",
  "Northern Irish": "🇬🇧",
  Irish: "🇮🇪",
  // Western Europe
  German: "🇩🇪",
  Dutch: "🇳🇱",
  French: "🇫🇷",
  Spanish: "🇪🇸",
  Italian: "🇮🇹",
  Portuguese: "🇵🇹",
  Belgian: "🇧🇪",
  Austrian: "🇦🇹",
  Swiss: "🇨🇭",
  Greek: "🇬🇷",
  Turkish: "🇹🇷",
  // Eastern Europe
  Croatian: "🇭🇷",
  Serbian: "🇷🇸",
  Czech: "🇨🇿",
  Slovak: "🇸🇰",
  Polish: "🇵🇱",
  Hungarian: "🇭🇺",
  Romanian: "🇷🇴",
  Bulgarian: "🇧🇬",
  Russian: "🇷🇺",
  Ukrainian: "🇺🇦",
  Slovenian: "🇸🇮",
  Bosnian: "🇧🇦",
  Albanian: "🇦🇱",
  Macedonian: "🇲🇰",
  Montenegrin: "🇲🇪",
  Georgian: "🇬🇪",
  Armenian: "🇦🇲",
  // Scandinavia
  Swedish: "🇸🇪",
  Norwegian: "🇳🇴",
  Danish: "🇩🇰",
  Finnish: "🇫🇮",
  Icelandic: "🇮🇸",
  // South America
  Brazilian: "🇧🇷",
  Argentine: "🇦🇷",
  Uruguayan: "🇺🇾",
  Chilean: "🇨🇱",
  Colombian: "🇨🇴",
  Paraguayan: "🇵🇾",
  Bolivian: "🇧🇴",
  Peruvian: "🇵🇪",
  Ecuadorian: "🇪🇨",
  Venezuelan: "🇻🇪",
  // North / Central America / Caribbean
  Mexican: "🇲🇽",
  American: "🇺🇸",
  Canadian: "🇨🇦",
  Jamaican: "🇯🇲",
  Trinidadian: "🇹🇹",
  Costa_Rican: "🇨🇷",
  // Africa
  Senegalese: "🇸🇳",
  Cameroonian: "🇨🇲",
  Ivorian: "🇨🇮",
  Ghanaian: "🇬🇭",
  Nigerian: "🇳🇬",
  Moroccan: "🇲🇦",
  Algerian: "🇩🇿",
  Tunisian: "🇹🇳",
  Egyptian: "🇪🇬",
  Malian: "🇲🇱",
  Guinean: "🇬🇳",
  Congolese: "🇨🇩",
  "South African": "🇿🇦",
  Zimbabwean: "🇿🇼",
  Zambian: "🇿🇲",
  Mozambican: "🇲🇿",
  Angolan: "🇦🇴",
  Gabonese: "🇬🇦",
  Togolese: "🇹🇬",
  Burkinabe: "🇧🇫",
  Liberian: "🇱🇷",
  Kenyan: "🇰🇪",
  Ethiopian: "🇪🇹",
  // Asia / Oceania
  Japanese: "🇯🇵",
  Korean: "🇰🇷",
  Chinese: "🇨🇳",
  Iranian: "🇮🇷",
  Saudi: "🇸🇦",
  Australian: "🇦🇺",
  "New Zealander": "🇳🇿",
};

export function nationalityFlag(nationality: string): string {
  return FLAGS[nationality] ?? "🏳️";
}
